[package]
name = "progettoRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.40.0", features = ["full"]}
scrap = "0.5.0"
x11 = "2.21.0"
image = "0.25.2"